### PR TITLE
Major version update

### PR DESCRIPTION
**Pull request by k3a**
Here is the full changeset I made. It is rather big so if you decide to merge it, the version should be bumped to 2.1.0 or even 3.0.0.

Initially I made changes I need for my authn/authz setup but I noticed couple of TODOs in the source and complains so I attempted to solve most of them during the process.

What is inside the included commits:
- formatting, linting, documenting: just function renames, argument reorders, no functional change except response from `notAuthenticated` function can return JSON or XML response if the request `Accept` header allows that.
- case-insensitive username and groupname comparisons for RBAC: what it says [also see NOTE1 below]
- pass the logger optionally: what it says
- wildcard matching improved: please read the full commit message [also see NOTE2 below]
- use single securecookie for session data: please read the full commit message
- get rid of global config variable: your TODOed thing. It is a bit painful to pass parts of config via function arguments but this is probably best way to do it for now. That can be eventually further refactored at will. But this should be pretty fine starting point.

**NOTE1**: As in the previous pull request, this is theoretically optional commit. Maybe some people would like exact comparisons on user names and group names (I don't know?) but my username started with uppercharacter so I had to make it case-insensitive comparison and I thought it probably wouldn't hurt to make default for everyone. It's up to you but I would keep it.

**NOTE2**: Wildcard matching (and optional regexp matching) is a big thing. I can later properly document it in README too but I tried to describe it in the commit message. It breaks backward-compatibility, becase previously you allowed 1 or none wildcard '*' character and /path based matching only. I wanted to support full URL matching and realized that writing a rule like `*://protected.com/` would basically match everything including something like `https://allowed.com/fakepath/://protected.com` so it was not safe. So I decided to implement something like seen in the Glob implementations - `*` matches inside one path component only (i.e. not matching '/' character) and `**` matching anything. Your previously specified rules now has to be replaced by `**` to work the same way. There was a possibility to keep one `*` (backward-compatible) for /path matching and use the new way for full URL matching but I think that might add confusion (I think people would mostly expect consistent behavior for both cases instead of different meaning of * between /path and full URL match). So this commit contains the new `*` and `**` semantics which is not backward-compatible. Let me know what do you think. Full URL matching is useful to protect multiple domains with a single TFA deployment.

**Tests were updated to the updated functionality** but their coverage should be roughly the same.

If anything is not clear or you want it differently, shout. It works ok for me this way so I can always have my own fork but I think up-streaming makes sense. I am ok to do some modifications but I won't spend multiple weeks on it. :P I need to move on with actually writing rules and using it. :)

### CODE REVIEW

**Comment by jr0d** [comment]
@k3a First off, thanks for these contributions and the detailed write up. This is really great work and likely very useful for others using this fork. 

Regarding case insensitivity, I think this may only raise issues with SAML backends exposed through [dex](https://github.com/dexidp/dex). There may be other back ends with case sensitive user lookups, so it's probably better to make this optional. 

Pattern matching in RBAC was built to mirror the functionality in k8s for nonResourceURLs. Since the policies are additive (no explicit deny), this certainly has some limitations. Have you tested adding a rbac.kubernetes.io/ClusterRole with regex in the nonResourceURL? 

I still need to complete my review, but overall, I am fine merging this in as version 3.0.0.

**Comment by k3a** [comment]
Ok, [I have made](https://github.com/mesosphere/traefik-forward-auth/compare/7f95ef54aacc96c4c2123be8ca653421e2657b73..b169d93d0e3b8b08bb92c4a271e70b427fd36a23) case-insensitive user/group comparison configurable with default being False. So the comparison has to be the exact match (as before) by default. The operator can optionally set case-insensitive-subjects (CASE_INSENSITIVE_SUBJECTS env) to true to enable case-insensitive comparison for user and group names.

> Pattern matching in RBAC was built to mirror the functionality in k8s for nonResourceURLs. Since the policies are additive (no explicit deny), this certainly has some limitations. Have you tested adding a rbac.kubernetes.io/ClusterRole with regex in the nonResourceURL?

I was able to use any type of matching in the nonResourceURL, including regexp one (which is prefixed by `~` character. Here is the shortened Rule I tested on Kubernetes 1.17.5 (no complains from any validator):

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sso-kibana
rules:
- nonResourceURLs:
  - '*://kibana.domain.com/elasticsearch/_msearch'
  - '*://kibana.domain.com/elasticsearch/*/_search'
  - '*://kibana.domain.com/api/kibana/management/saved_objects/**'
  - ~/k[0-9]a$
  verbs:
  - GET
  - HEAD
  - POST
```

It made sense to mirror the functionality of original nonResourceURLs but it has limitations of course, as it was made for protecting simple paths like `/healthz` and `/ping`. It looks like Kubernetes considers nonResourceURLs a [simple array of strings](https://github.com/kubernetes/api/blob/b6206047d210c77610af39908f11a34d0961f8bc/authorization/v1/types.go#L267). At runtime, those strings are still [happily parsed](https://play.golang.org/p/Uhy6QtxAbBS) as "url paths" by Go url package (although those strings are not 100% correct URLs according to RFC rules as some characters would have to be URL-escaped normally but Go url package seem to be lenient).

So in my opinion it should be usable to "abuse" `nonResourceURLs` for patterns like these. In the worst case, if things change, we can still make a CRD with similar structure `rbac.authorization.k8s.io/v1` but there is some annoyance associated with CRDs and their updates. These RBAC rules are rather primitive to require a CRD IMO unless forced by external matters. :P

**Comment by jr0d** [comment]
@k3a I've created a new branch, v3.0.0 and a pre-release tag, v3.0.0-rc.1. An image has been pushed, mesosphere/traefik-forward-auth:3.0.0-rc.1. I am going to let this bake for a little while and do some more testing using this branch. Once v3.0.0 is official, I'll merge v3 into master; referencing this PR.

**Comment by k3a** [comment]
Ok, thanks. I am actively using this pull request and so far it has been working nicely for us.

On top of what you have merged, I created one more commit (#33). I kept is separate in order not to inflate the previous pull request even more. It is also a bit special so better to consider/discuss separately.

**Pull request closed without merging**
