### PR TITLE
fix invalid error log message

### PR DESCRIPTION
**Pull request by foosinn**
a run of go test ./... failed for me due to an invalid Errorf statement.

### CODE REVIEW

**Comment by k3a** [comment]
You should probably use %v to make it consistent with other errors. 
There doesn't seem to be difference now (https://play.golang.org/p/01OEs7caVsA) but I think there used to be difference in previous Go versions.

**Comment by foosinn** [comment]
Updated to use `%v`

**Comment by mhrabovcin** [comment]
@jr0d can we merge this one?

**Comment by jr0d** [comment]
Thanks @foosinn

**Pull request merged**
